apiVersion: v1
kind: Service
metadata:
  name: github-trending-feed-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: github-trending-feed-backend