apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-trending-feed-backend-deployment
spec:
  replicas: 2
  minReadySeconds: 15
  selector:
    matchLabels:
      app: github-trending-feed-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: github-trending-feed-backend
    spec:
      containers:
        - image: registry.gitlab.com/rremizov/github-trending-feed:latest
          imagePullPolicy: IfNotPresent
          name: github-trending-feed-backend
          ports:
            - containerPort: 3000